frontend/src/components/table/list/list-component.tsx
frontend/src/components/table/list/schedule-cell-component.tsx
frontend/src/components/table/list/schedule-row-component.tsx
frontend/src/components/toolbar/import-buttons/import-buttons.component.tsx
frontend/src/components/toolbar/problem-metadata/problem-metadata.component.tsx
frontend/src/hooks/file-processing/useScheduleConverter.ts
frontend/src/logic/schedule/schedule.logic.ts
frontend/src/logic/schedule/shifts-info.logic.ts
frontend/src/state/app-reducer.tsx
frontend/src/state/models/application-state.model.ts
frontend/src/state/reducers/schedule-data.reducer.ts
frontend/src/state/reducers/xlxs-sheet-data-reducer.ts

Nie dodałem dużo rzeczy, ale trochę zmieniłem to jak wygląda stan aplikacji: teraz do niego jest dodawany również sparsowany excel. 
Dodałem też bazowy widok tabeli, do którego trochę później będę dodawać style i funkcjonalności.

Add basic table and add parsed json to application state

---

frontend/src/components/toolbar/import-buttons/import-buttons.component.tsx
frontend/src/components/toolbar/problem-metadata/problem-metadata.component.tsx

Standardize language of UI elements

---

frontend/src/components/table/schedule/schedule-state.model.ts
frontend/src/components/table/schedule/schedule.component.tsx
frontend/src/components/table/schedule/sections/extra-workers-section/extra-workers-section.components.tsx
frontend/src/components/table/schedule/sections/extra-workers-section/extra-workers-section.options.ts
frontend/src/components/table/schedule/use-schedule-state.ts
frontend/src/logic/real-schedule-logic/extra-workers.logic.ts
frontend/src/logic/real-schedule-logic/schedule.logic.ts
frontend/src/logic/schedule-parser/extra-workers.parser.ts
frontend/src/logic/schedule-parser/schedule.parser.ts
frontend/src/logic/schedule-provider.ts
frontend/src/state/models/schedule-data/month-info.model.ts

https://nurse-scheduling.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=NS&modal=detail&selectedIssue=NS-33

Handle extra workers NS-33

---

.gitignore
cypress/integration/unit/logic/schedule-logic/public-holidays.spec.ts

Dodałem UT dla obsługi świąt i wrzuciłem katalog na filmiki cypressa do gitignore

TASK-2 Unit tests for handling public holidays

---

src/common-models/schedule-error.model.ts
src/components/toolbar/import-buttons/hooks/use-schedule-converter.ts
src/helpers/error-message.helper.ts
src/helpers/tranlsations.helper.ts
src/logic/schedule-exporter/schedule-export.logic.ts
src/logic/schedule-logic/month-info.logic.ts
src/logic/schedule-parser/schedule.parser.ts

Wprowadziłem te zmiany o których pisałem w komentarzach, bo @Sig00rd na swoim branchu wprowadził zmianę struktury katalogów i chcielibyśmy najpierw zmerogwać wszystkie PR, żeby potem nie było konfliktów

Replaces raw strings with Enums, removes months Enum

---

package-lock.json
package.json
src/api/local-storage-provider.model.ts
src/api/persistance-store.model.ts
src/common-models/schedule-data.model.ts
src/common-models/shift-info.model.ts
src/common-models/worker-info.model.ts
src/components/add-worker-modal/add-worker-modal.tsx
src/components/table/schedule/sections/shifts-section/shifts-section.component.tsx
src/components/table/schedule/use-schedule-state.ts
src/index.tsx
src/logic/schedule-logic/schedule.logic.ts
src/state/app-store.tsx
src/state/reducers/employee-info.reducer.ts

Nie jest to wersja końcowa, a tylko koncepcja którą ja widzę. Robiłem na podstawie tego artykułu:
https://redux.js.org/tutorials/fundamentals/part-6-async-logic
Ogólnie, to chciałbym omówić go na jutrzejszym spotkaniu, i chciałbym tez poczytać o innych możliwościach pracy offline: service workerach, ponieważ słyszałem, że za ich pomocą, można operować na systemie plików, a nie jestem pewny tego, czy da się wykorzystać z nimi ten mechanizm co ja wykorzystałem tutaj. 
Chciałbym też dowiedzieć się trochę więcej o tym, czy da się wykorzystać w tym miejscu IndexedDb.

TASK-64 basic repository

---

src/components/schedule-page/table/schedule/schedule-parts/shift-row.component.tsx
src/helpers/shifts.helper.ts

Jak w tytule, dajcie znać czy o to chodziło

TASK-102 Move work hours info calculation to ShiftHelper

---

cypress.json
cypress/integration/e2e/header-control-menu/menu-plik.spec.js
cypress/integration/e2e/table/change-shift.spec.js

Może póki jestem przy tym zadaniu to dodać jakieś zmienne jeszcze?

TASK-88 cypress environment variables fixed

---

cypress/integration/unit/helpers/shift.helper.spec.ts
src/api/backend.ts
src/components/schedule-page/table/schedule/schedule-parts/base-row.component.tsx
src/components/schedule-page/table/schedule/schedule-parts/shift-row.component.tsx
src/components/schedule-page/table/schedule/sections/base-section/base-section.component.tsx
src/components/schedule-page/table/schedule/sections/date-section/date-section.component.tsx
src/components/schedule-page/table/schedule/sections/foundation-info-section/foundation-info.component.tsx
src/components/schedule-page/table/schedule/sections/shifts-section/shifts-section.component.tsx
src/helpers/shifts.helper.ts
src/helpers/verbose-date.helper.ts
src/logic/schedule-logic/schedule.logic.ts
src/logic/schedule-logic/shifts-info.logic.ts

Dodam jeszcze test do tego, ale nie wcześniej niż w poniedziałek, więc myślę, że żeby nie zatrzymywać @Sig00rd można zmergować to w takim stanie.

Task 116 work hour calculation

---

src/assets/styles/styles/custom/_tables.scss
src/assets/styles/styles/custom/_variables.scss
src/components/common-components/dropdown-buttons/dropdown-buttons.component.tsx
src/components/overtime-header-table/overtime-header-cell.component.tsx
src/components/overtime-header-table/overtime-header-row.component.tsx
src/components/overtime-header-table/overtime-header.component.tsx
src/components/schedule-page/table/schedule/schedule.component.tsx
src/components/timetable/timetable-cell.component.tsx

easy and fun to review
added one table component 
and additional style changes

Task 143 add overtime header time table

---

src/assets/styles/styles/custom/_tables.scss
src/assets/styles/styles/custom/_variables.scss
src/components/schedule-page/table/schedule/schedule-parts/base-cell/base-cell.component.tsx

add error triangles + fix table style unwanted change

TASK-23 add error triangles + fix table style unwanted change

---

.env
.gitignore
cypress.json
cypress/fixtures/.gitignore
cypress/integration/user-acceptance/schedule-display-requirement.spec.ts
cypress/integration/user-acceptance/schedule-editing-requirement.spec.ts
cypress/integration/user-acceptance/schedule-import-export-requirement.spec.ts
cypress/integration/user-acceptance/worker-management-requirement.spec.ts
cypress/support/commands.ts
cypress/support/index.d.ts
cypress/support/index.ts
package-lock.json
package.json
src/components/common-components/dropdown-buttons/dropdown-buttons.component.tsx
src/components/namestable/worker-edit.component.tsx
src/components/workers-page/workers-tab/enhanced-table-header.component.tsx
src/components/workers-page/workers-tab/workers-tab.component.tsx

Wszystkie wymagania. Obok tych, co już zostały przetestowane stoi `V`.
Panel zarządzania
==
Kryteria akceptacji:
-  [ ]  aplikacja umożliwia dodawanie i usuwanie rodzajów zmian, podczas których pracownik jest w ośrodku. Zmiany te powinny być powiązane z czasem ich trwania, np. zmiana nocna N trwająca od 22:00 do 06:00
-  [ ]   aplikacja umożliwia ustalanie symboli (skrótowych nazw) dla zmian, które potem wyświetlane są na grafiku
-  [ ]  aplikacja umożliwia dostosowanie kolorystyki symboli (np. poprzez wybór z listy tematów kolorystycznych)
-  [ ]  aplikacja umożliwia zdefiniowanie czasu trwania dnia i nocy w ośrodku
Tryb podglądu harmonogramu
==
Kryteria akceptacji:
Tryb edycji grafiku
==
Kryteria akceptacji:

Task 208 user acceptance tests

---

cypress/integration/e2e/table/update-workhours-info.spec.ts
src/assets/styles/styles/custom/_autocomplete.scss
src/assets/styles/styles/custom/_schedule-style.scss
src/assets/styles/styles/custom/_tables.scss
src/assets/styles/styles/custom/_variables.scss
src/components/common-components/autocomplete/autocomplete.component.tsx
src/components/schedule-page/table/schedule/schedule-parts/base-cell/base-cell.component.tsx
src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-autocomplete.component.tsx

TASK-203-dropdown-styling-update

---

src/assets/styles/styles/custom/_tables.scss
src/components/schedule-page/table/schedule/schedule-parts/error-tooltip-provider.component.tsx
src/components/schedule-page/table/schedule/sections/shifts-section/shifts-section.component.tsx

na razie są drobne paski między dniami

TASK-179 Add weekly badges

---

src/components/schedule-page/table/schedule/sections/foundation-info-section/foundation-info.component.tsx
src/components/timetable/timetable-cell.component.tsx

Informacje o błędach dot. pielęgniarek dodane do headera tabeli, badge z komponentu informacji fundacji wywalone

TASK-293 Move nurse count error badges to table header

---

src/assets/styles/styles/custom/_month-switch.scss
src/components/schedule-page/new-month-plan.component.tsx

This reverts commit 6ee577d5fb8627903ba1249d7a111d97d4d80059.

Revert "TASK-300 Add no schedule image as link (don't merge) (#228)"

---

cypress/integration/e2e/table/load-schedule.spec.ts
src/components/common-components/drawer/jira-like-drawer.component.tsx

Teraz drawer się zamyka po opuszczeniu trybu edycji.

TASK-389 Bug fixed. Cypress local passing.

---

src/assets/styles/styles/custom/_dropdown.scss
src/common-models/worker-info.model.ts
src/components/common-components/dropdown-buttons/dropdown-buttons.component.tsx
src/components/namestable/use-worker-info.ts
src/components/namestable/worker-edit/worker-civil-contract-work-norm-selector.component.tsx
src/components/namestable/worker-edit/worker-edit.component.tsx
src/components/namestable/worker-edit/worker-edit.models.ts
src/components/namestable/worker-edit/worker-group-selector.component.tsx
src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx
src/components/schedule-page/table/schedule/use-worker-groups.ts
src/components/workers-page/workers-tab/enhanced-table-header.component.tsx
src/components/workers-page/workers-tab/workers-tab.component.tsx
src/logic/schedule-parser/shifts-info.parser.ts
src/logic/schedule-parser/workers-info.parser.ts
src/state/reducers/worker.action-creator.ts

…allows to change worker group

TASK-408 Add information about worker team to management table

---

src/components/schedule-page/table/schedule/schedule-parts/base-cell/base-cell-input.component.tsx
src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-autocomplete.component.tsx
src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx
src/logic/schedule-parser/shifts-info.parser.ts

TASK-431 Increase dropdown timeout from 444ms to 4444ms

---

src/components/schedule-page/table/schedule/schedule-parts/error-tooltip-provider.component.tsx
src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx

Od teraz nie ma możliwości kliknięcia w "trójkąt" i pozostawienie errora otwartego.  Error znika także kiedy pojawia się dropdown.

TASK-229 BUG: error tooltip onclick removal
